# Form implementation generated from reading ui file 'lesson1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_lesson1(object):
    def setupUi(self, lesson1):
        lesson1.setObjectName("lesson1")
        lesson1.resize(750, 470)
        self.centralwidget = QtWidgets.QWidget(parent=lesson1)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 750, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        lesson1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=lesson1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        lesson1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=lesson1)
        self.statusbar.setObjectName("statusbar")
        lesson1.setStatusBar(self.statusbar)

        self.retranslateUi(lesson1)
        QtCore.QMetaObject.connectSlotsByName(lesson1)

    def retranslateUi(self, lesson1):
        _translate = QtCore.QCoreApplication.translate
        lesson1.setWindowTitle(_translate("lesson1", "MainWindow"))
        self.label.setText(_translate("lesson1", "Урок 1: Основы SQL — Выборка данных\n"
"Цель урока: Научиться извлекать данные из таблиц с помощью запроса SELECT.\n"
"\n"
"Что такое запрос SELECT?\n"
"Запрос SELECT используется для извлечения данных из одной или нескольких колонок таблицы.\n"
"\n"
"Простой запрос для выборки всех данных:\n"
"SELECT column1, column2, ... FROM table_name;\n"
"Для выбора всех данных из таблицы можно использовать *, что означает «все колонки».\n"
"\n"
"Примеры запросов\n"
"Выбор всех колонок:\n"
"SELECT * FROM employees;\n"
"Этот запрос выберет все строки и все колонки из таблицы employees.\n"
"\n"
"Выбор определённых колонок: Если нужно выбрать только некоторые данные, указывайте имена колонок через запятую:\n"
"SELECT name, age FROM employees;\n"
"Этот запрос вернёт только имена и возраст сотрудников.\n"
"\n"
"Выбор данных с псевдонимами (алиасами): Для удобства можно использовать псевдонимы для отображения колонок:\n"
"SELECT name AS \"Employee Name\", age AS \"Employee Age\" FROM employees;\n"
"Этот запрос отобразит столбцы с именами \"Employee Name\" и \"Employee Age\" вместо стандартных названий колонок.\n"
"\n"
"Важные моменты:\n"
"* используется для выбора всех колонок таблицы.\n"
"Псевдонимы (aliase) упрощают чтение результатов запроса."))
