# Form implementation generated from reading ui file 'lesson5.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 570)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 790, 550))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Урок 5: Соединение таблиц с помощью оператора JOIN\n"
"Цель урока: Научиться объединять данные из нескольких таблиц с помощью операторов соединения JOIN.\n"
"\n"
"Оператор JOIN используется для объединения строк из двух и более таблиц на основе логического условия.\n"
"\n"
"Примеры использования оператора JOIN\n"
"Пример 1: Простое соединение JOIN\n"
"Для объединения данных из двух таблиц employees и departments,\n"
"где каждый сотрудник имеет ссылку на отдел через поле department_id:\n"
"SELECT employees.name, departments.name\n"
"FROM employees\n"
"JOIN departments ON employees.department_id = departments.id;\n"
"Этот запрос выберет имена сотрудников и названия их отделов.\n"
"\n"
"Пример 2: Соединение с фильтрацией\n"
"Можно добавить условие фильтрации после соединения. Например,\n"
"чтобы выбрать только тех сотрудников, которые работают в отделе \"HR\":\n"
"SELECT employees.name, departments.name\n"
"FROM employees\n"
"JOIN departments ON employees.department_id = departments.id\n"
"WHERE departments.name = \'HR\';\n"
"\n"
"Пример 3: Разные типы соединений\n"
"LEFT JOIN: Все строки из левой таблицы и совпадающие строки из правой.\n"
"RIGHT JOIN: Все строки из правой таблицы и совпадающие строки из левой.\n"
"FULL JOIN: Все строки из обеих таблиц.\n"
"\n"
"Пример с использованием LEFT JOIN:\n"
"SELECT employees.name, departments.name\n"
"FROM employees\n"
"LEFT JOIN departments ON employees.department_id = departments.id;\n"
"Этот запрос вернет все имена сотрудников и название их отдела, если они принадлежат какому-либо отделу.\n"
"Если сотрудник не относится ни к одному отделу, то для него будет выведено значение NULL в колонке с названием отдела.\n"
"\n"
""))
