# Form implementation generated from reading ui file 'lesson4.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_lesson4(object):
    def setupUi(self, lesson4):
        lesson4.setObjectName("lesson4")
        lesson4.resize(620, 530)
        self.centralwidget = QtWidgets.QWidget(parent=lesson4)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 600, 470))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        lesson4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=lesson4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName("menubar")
        lesson4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=lesson4)
        self.statusbar.setObjectName("statusbar")
        lesson4.setStatusBar(self.statusbar)

        self.retranslateUi(lesson4)
        QtCore.QMetaObject.connectSlotsByName(lesson4)

    def retranslateUi(self, lesson4):
        _translate = QtCore.QCoreApplication.translate
        lesson4.setWindowTitle(_translate("lesson4", "MainWindow"))
        self.label.setText(_translate("lesson4", "Урок 4: Агрегатные функции — COUNT, AVG, SUM, MAX, MIN\n"
"Цель урока: Научиться использовать агрегатные функции для получения статистических данных.\n"
"\n"
"Агрегатные функции применяются к набору строк и возвращают одно значение для этого набора. \n"
"\n"
"К основным агрегатным функциям относятся:\n"
"COUNT — подсчет строк.\n"
"AVG — вычисление среднего значения.\n"
"SUM — вычисление суммы.\n"
"MAX — нахождение максимума.\n"
"MIN — нахождение минимума.\n"
"\n"
"Примеры использования агрегатных функций\n"
"\n"
"Пример 1: Подсчет количества строк\n"
"Подсчитываем общее количество записей в таблице employees:\n"
"SELECT COUNT(*) FROM employees;\n"
"\n"
"Пример 2: Среднее значение\n"
"Вычисляем средний возраст сотрудников:\n"
"SELECT AVG(age) FROM employees;\n"
"\n"
"Пример 3: Сумма значений\n"
"Вычисляем общую сумму зарплат сотрудников (предполагается наличие колонки salary):\n"
"SELECT SUM(salary) FROM employees;\n"
"\n"
"Пример 4: Максимальное и минимальное значение\n"
"Находим максимальный и минимальный возраст сотрудников:\n"
"SELECT MAX(age), MIN(age) FROM employees;"))
