# Form implementation generated from reading ui file 'lesson3.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_lesson3(object):
    def setupUi(self, lesson3):
        lesson3.setObjectName("lesson3")
        lesson3.resize(700, 400)
        self.centralwidget = QtWidgets.QWidget(parent=lesson3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 670, 350))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        lesson3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=lesson3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        lesson3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=lesson3)
        self.statusbar.setObjectName("statusbar")
        lesson3.setStatusBar(self.statusbar)

        self.retranslateUi(lesson3)
        QtCore.QMetaObject.connectSlotsByName(lesson3)

    def retranslateUi(self, lesson3):
        _translate = QtCore.QCoreApplication.translate
        lesson3.setWindowTitle(_translate("lesson3", "MainWindow"))
        self.label.setText(_translate("lesson3", "Урок 3: Сортировка данных с помощью оператора ORDER BY\n"
"Цель урока: Научиться сортировать данные по возрастанию или убыванию с помощью оператора ORDER BY.\n"
"\n"
"Основной синтаксис запроса:\n"
"SELECT column1, column2 FROM table_name ORDER BY column1 ASC|DESC;\n"
"Оператор ORDER BY позволяет отсортировать данные по одному или нескольким столбцам. \n"
"По умолчанию сортировка идет по возрастанию (ASC), но можно указать сортировку по убыванию (DESC).\n"
"\n"
"Примеры использования оператора ORDER BY\n"
"\n"
"Пример 1: Сортировка по возрастанию\n"
"Сортируем сотрудников по возрасту от младшего к старшему:\n"
"SELECT name, age FROM employees ORDER BY age ASC;\n"
"\n"
"Пример 2: Сортировка по убыванию\n"
"Сортируем сотрудников по возрасту от старшего к младшему:\n"
"SELECT name, age FROM employees ORDER BY age DESC;\n"
"\n"
"Пример 3: Сортировка по нескольким столбцам\n"
"Сортировка сначала по возрасту (по возрастанию), затем по имени (по убыванию):\n"
"SELECT name, age FROM employees ORDER BY age ASC, name DESC;"))
